backend:
  name: github
  repo: yaycake/portfolio-2020

media_folder: static/assets
public_folder: /assets

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: featuredImage, label: Featured Image, widget: "image" }
      - { name: skills, label: Skills }
      - { name: tools, label: tools }
      - { name: engagement_period, label: Engagement Period }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
